server:
  port: 8087

Spring:
  application:
    name: service-product

  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/mybatistudymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      hbm2ddl:
        auto: update
        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect

#mybatis:
#  mapper-locations:
#    - classpath:mapper/*.xml
#    - classpath*:com/**/mapper/*.xml
