server:
  port: 8093
  tomcat:
    threads:
      max: 10 #tomcat的最大并发数修改为10，默认是200

Spring:
#  profiles:
#    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: shop-order
  zipkin:
    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0  #采样的百分比
  cloud:
      nacos:
        discovery:
          server-addr:  127.0.0.1:8848
      sentinel:
        transport:
          port: 19999 #跟控制台交流的端口，随意指定一个未使用的端口即可
          dashboard:  localhost:8080 #指定控制台服务的地址
          clientIP: 169.254.153.210

        #禁止收敛URL的入口context
        web-context-unify:  false

  ##Ribbon均衡负载
  service-product: shop-product

  ribbon:

    NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule



  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/mybatistudymall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect:  org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      open-in-view: false

# 开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#rocketmq
rocketmq:
  name-server: 127.0.0.1:9876   #rocketMQ服务的地址
  producer:
    group: shop-order # 生产者组


